/*DROP TABLE orders if EXISTS;

CREATE TABLE orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customerName VARCHAR(100),
 amount DECIMAL(10, 2)
);*/

CREATE TABLE hospital (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nom VARCHAR(255),
                          service VARCHAR(255),
                          dateAdmission VARCHAR(255),
                          dateSortie VARCHAR(255)
);